name: Salesforce CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Setup Nodee
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. Install Salesforce CLI
      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      # 4. Create JWT key file
      - name: Create JWT Key
        run: echo "${{ secrets.SF_JWT_KEY }}" > server.key

      # 5. Authenticate
      - name: Authenticate Org
        run: |
          sf org login jwt \
          --client-id ${{ secrets.SF_CLIENT_ID }} \
          --jwt-key-file server.key \
          --username ${{ secrets.SF_USERNAME }} \
          --instance-url ${{ vars.SF_INSTANCE_URL }}

      # 6. Validate Deployment
      - name: Validate Deployment
        run: |
          sf project deploy start \
          --source-dir force-app \
          --check-only \
          --test-level RunLocalTests \
          --wait 20

      # 7. Run Apex Tests
      - name: Run Apex Tests
        run: |
          sf apex run test \
          --result-format human \
          --wait 20

      # 8. Deploy
      - name: Deploy to Salesforce
        run: |
          sf project deploy start \
          --source-dir force-app \
          --wait 20

      # 9. Show Org Info 
      - name: Display Org Info
        run: sf org display