name: Salesforce CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Install SFDX Git Delta
        run: npm install -g sfdx-git-delta

      - name: Create JWT Key
        run: echo "${{ secrets.SF_JWT_KEY }}" > server.key

      - name: Authenticate Org
        run: |
          sf org login jwt \
            --client-id ${{ secrets.SF_CLIENT_ID }} \
            --jwt-key-file server.key \
            --username ${{ secrets.SF_USERNAME }} \
            --instance-url ${{ vars.SF_INSTANCE_URL }} \
            --set-default

      - name: Verify Org
        run: sf org display

      - name: Install SFDX Git Delta
        run: |
          echo y | sf plugins install sfdx-git-delta

      - name: Create Delta Folder
        run: mkdir delta

      - name: Generate Delta Package
        run: |
          sf sgd source delta \
            --to HEAD \
            --from HEAD~1 \
            --output-dir delta \
            --generate-delta

      - name: Validate Deployment
        run: |
          sf project deploy validate \
            --manifest delta/package/package.xml \
            --target-org ${{ secrets.SF_USERNAME }} \
            --test-level RunLocalTests \
            --wait 20

      - name: Deploy to Salesforce
        run: |
          sf project deploy start \
            --manifest delta/package/package.xml \
            --target-org ${{ secrets.SF_USERNAME }} \
            --wait 20